---
title: "Lecture 15 (Iteration) - Writing Functions"
author: "CJ Snyder"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(p8105.datasets)
set.seed(1)
```

# My First Function, but first some foundations...
```{r}

x = rnorm(n = 30, mean = 4, sd = 2.3)

x_again = rnorm(n = 30, mean = 6, sd = 0.3)

y = rnorm(n = 30, mean = 8, sd = 1.6)


(x - mean(x)) / sd(x)

(x_again - mean(x_again)) / sd(x_again)

(y - mean(y)) / sd(y)

```

## Actual Function...
```{r}
z_score = function(x) {
  (x - mean(x)) / sd(x)
}

z_score(x)
z_score(x_again)
z_score(y)

```

```{r, error=TRUE}
z_score(3)

z_score("my name is not Jeff")

z_score(x=c(TRUE, TRUE, TRUE, FALSE))
# Actually works cause R can convert T/F to numeric

z_score(x=iris)
```

### Editing the Function with Conditions
```{r}
z_score = function(x) {
  if (!is.numeric(x)) {
    stop("Argument should be Numeric")
  } else if (length(x<3)) {
    stop("X should be Less than 3")
  }
  (x - mean(x)) / sd(x)
}
```

# Multiple Outputs
```{r}
mean_and_sd = function(input_x) {
   if (!is.numeric(input_x)) {
    stop("Argument should be Numeric")
  } else if (length(input_x) < 3) {
    stop("X should be Less than 3")
  }
  tibble(
  mean_input=mean(input_x),
  sd_input=sd(input_x)
  )
}
```

testing..
```{r}
mean_and_sd(x)
mean_and_sd(y)
```

# Multiple Inputs
```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
# Estimated Intercept
beta1_hat = coef(ls_fit)[2]
# Estimated slope
```

# Sim Regression
```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

## Testing Sim Regression
```{r}
sim_regression(15, beta0 = 3, beta1 = 4)
sim_regression(30, beta0 = 3, beta1 = 4)
sim_regression(60, beta0 = 2, beta1 = 5)
sim_regression(4000, beta0 = 3, beta1 = 6)
sim_regression(100000, 25.6, 30)
sim_regression(100000)
```


# Scrape lots of info from Amazon
```{r}
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

## Testing New Function
```{r}
read_page_reviews("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1")
```

















